### ISSUE TITLE
@import should work with relative paths

### ISSUE THREAD

**Issue by eramdam** [MoOx/postcss-cssnext#21]
Tested with gulp-cssnext, I noticed that @import rules don't work if the path is being relative to the .css file. Given the following structure

```
.
├── css
│   ├── import.css
│   └── sub-folder
│       ├── import-abs.css
│       └── import-rel.css
├── gulpfile.js
├── out
│   └── import-abs.css
└── package.json
```

With `import-abs.css` having

``` css
@import "css/import.css";
```

And `import-rel.css` having

``` css
@import "../import.css";
```

And the `gulpfile.js` having this

``` js
var gulp = require("gulp");
var cssnext = require("gulp-cssnext")

gulp.task("css:relative", function() {
  gulp.src("css/sub-folder/import-rel.css")
    .pipe(cssnext({
        compress : true
    }))
    .pipe(gulp.dest("./out"))
});

gulp.task("css:absolute", function() {
  gulp.src("css/sub-folder/import-abs.css")
    .pipe(cssnext({
        compress : true
    }))
    .pipe(gulp.dest("./out"))
});
```

Then, `gulp css:relative` returns 

``` bash
[11:59:29] Using gulpfile ~/Desktop/cssnext-import-bug/gulpfile.js
[11:59:29] Starting 'css:relative'...
[11:59:29] Finished 'css:relative' after 16 ms
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: undefined1:1: Failed to find ../import.css
    in [
        /Users/Damien/Desktop/cssnext-import-bug
    ]
    at resolveFilename (/Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss-import/index.js:133:11)
    at readAtImport (/Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss-import/index.js:82:26)
    at checkAtRule (/Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss-import/index.js:61:5)
    at /Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:374:30
    at /Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:110:26
    at Root.Container.each (/Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:88:20)
    at Root.Container.eachInside (/Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:109:21)
    at Root.Container.WithRules.constructor$0.eachAtRule (/Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:372:21)
    at parseStyles (/Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss-import/index.js:56:10)
    at /Users/Damien/Desktop/cssnext-import-bug/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss-import/index.js:45:5
```

And of course `gulp css:absolute` works like expected 

``` bash
[11:59:54] Using gulpfile ~/Desktop/cssnext-import-bug/gulpfile.js
[11:59:54] Starting 'css:absolute'...
[11:59:54] Finished 'css:absolute' after 14 ms
```

:tada:

**Comment by davidmaxwaterman** [comment]
The 'note' referred to above seems to have gone from the README. (I'm having trouble with grunt-cssnext, where it seems to change the paths in my css so they're wrong - not sure if the above pertains to my issue or not).

**Comment by MoOx** [comment]
@davidmaxwaterman gulp-cssnext has been deprecated. Please checkout how to migrate http://cssnext.io/postcss/ (and for you problem, just skip postcss-url).

**Comment by davidmaxwaterman** [comment]
For the record, my issue was not about migration (I am just adopting postcss-cssnext into this project). My mistake was requir()ing 'cssnext' instead of 'postcss-cssnext' - once I corrected that, the paths remained unchanged through the postcss-cssnext 'processor'.
