### ISSUE TITLE
Failed building docs

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/postcss-cssnext#305]
> ERROR in ./~/css-loader!./~/postcss-loader!./docs/src/index.css
Module build failed: TypeError: Cannot read property 'postcss' of undefined
    at Processor.normalize (D:\Dev\git\post-css\postcss-cssnext\node_modules\pos
tcss\lib\processor.js:219:12)
    at Processor.use (D:\Dev\git\post-css\postcss-cssnext\node_modules\postcss\l
ib\processor.js:169:45)
    at index.js:71:17
    at Array.forEach (native)
    at index.js:56:35
    at creator (D:\Dev\git\post-css\postcss-cssnext\node_modules\postcss\lib\pos
tcss.js:150:35)
    at Object.postcss (webpack.config.js:53:7)
    at Object.module.exports (D:\Dev\git\post-css\postcss-cssnext\node_modules\p
ostcss-loader\index.js:28:27)
 @ ./docs/src/index.css 4:14-124 13:2-17:4 14:20-130

**Comment by Semigradsky** [comment]
Sorry, I not changed function in src/features
