### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by htor** [MoOx/postcss-cssnext#307]
Getting an error when trying to run this code with `gulp`:

```js
gulp.task('css', function () {
  return (
    gulp.src('styles/**/*.css')
    .pipe(postcss([    // line 42
      require("postcss-cssnext")()
    ]))
    .pipe(gulp.dest('dist'))
  )
})
````

The error:

```bash

[12:36:18] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/Users/herman/projects/pjax-barba-test/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at Gulp.<anonymous> (/Users/herman/projects/pjax-barba-test/gulpfile.js:42:6)
    at module.exports (/Users/herman/projects/pjax-barba-test/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/herman/projects/pjax-barba-test/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/herman/projects/pjax-barba-test/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/herman/projects/pjax-barba-test/node_modules/orchestrator/index.js:134:8)
    at /Users/herman/.nvm/versions/node/v4.2.1/lib/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3
```

```bash

$ gulp -v
[12:39:59] CLI version 3.9.0
[12:39:59] Local version 3.9.1
$ node -v
v4.2.1
$ npm -v
2.14.7

```

**Comment by MoOx** [comment]
How is this a postcss-cssnext issue as the message said that gulp.dest is undefined?

**Comment by htor** [comment]
@MoOx My gulp code is basically a stripped down version of the example code from  http://cssnext.io/postcss/#gulp-postcss, so I'm curious why that doesn't run?

**Comment by MoOx** [comment]
According to this http://stackoverflow.com/questions/36908177/gulp-typeerror-dest-on-is-not-a-function
you may require(postcss) instead of gulp-postcss. Please provide a larger part of your code if you want some help.

**Comment by htor** [comment]
My bad,

I was using `postcss`, not `gulp-postcss`.

**Comment by MoOx** [comment]
;)
