### ISSUE TITLE
Color blend broken: Unable to parse color from a string

### ISSUE THREAD

**Issue by smutnyleszek** [MoOx/postcss-cssnext#363]
This is how I try to use it:

```css
a:active { 
    color: color(hsl(360, 100%, 100%) blend(hsl(120, 100%, 100%) 20%));
}
```

This is the error:

```error
{ Error: /Users/lpietrzak/Sites/priv/pobp/src/appSetup/states.css:24:12: Unable to parse color from string "hsl(120,"
    at /Users/lpietrzak/Sites/priv/pobp/src/appSetup/states.css:24:12
    at Color (/Users/lpietrzak/Sites/priv/pobp/node_modules/color/index.js:34:10)
    at Object.exports.blend (/Users/lpietrzak/Sites/priv/pobp/node_modules/css-color-function/lib/adjusters.js:39:15)
    at /Users/lpietrzak/Sites/priv/pobp/node_modules/css-color-function/lib/convert.js:56:20
    at Array.forEach (native)
    at toRGB (/Users/lpietrzak/Sites/priv/pobp/node_modules/css-color-function/lib/convert.js:42:7)
    at Object.convert (/Users/lpietrzak/Sites/priv/pobp/node_modules/css-color-function/lib/convert.js:28:10)
    at /Users/lpietrzak/Sites/priv/pobp/node_modules/postcss-color-function/index.js:38:26
    at walk (/Users/lpietrzak/Sites/priv/pobp/node_modules/postcss-value-parser/lib/walk.js:7:22)
    at ValueParser.walk (/Users/lpietrzak/Sites/priv/pobp/node_modules/postcss-value-parser/lib/index.js:18:5)
    at transformColor (/Users/lpietrzak/Sites/priv/pobp/node_modules/postcss-color-function/index.js:33:25)
  originalMessage: 'Unable to parse color from string "hsl(120,"',
  fileName: '/Users/lpietrzak/Sites/priv/pobp/src/appSetup/states.css',
  lineNumber: 24,
  columnNumber: 12 }
```

My `postcss.config.js`:

```js
module.exports = {
    plugins: {
        'postcss-import': {},
        'postcss-cssnext': {
            browsers: '> 5%'
        },
        cssnano: {
            autoprefixer: false
        }
    }
};
```

The related `devDependencies`:

```json
{
  "devDependencies": {
    "postcss": "^5.2.16",
    "postcss-cli": "^3.0.0-beta",
    "postcss-cssnext": "^2.9.0",
    "postcss-import": "^9.1.0"
  }
}
```

----

I did try `rgb()` colors too with the same result. Although if I use only a simple color names it does work:

```css
a:active { 
    color: color(red blend(blue 20%)); 
}
```

**Comment by MoOx** [comment]
Please report this error in https://github.com/ianstormtaylor/css-color-function (which is what we use under the hood)

**Comment by smutnyleszek** [comment]
Oh, ok. I even see there is an issue already https://github.com/ianstormtaylor/css-color-function/issues/24
