### ISSUE TITLE
@apply causes `Expected pseudo-class or pseudo-element`

### ISSUE THREAD

**Issue by avshyz** [MoOx/postcss-cssnext#371]
Adding these lines of codes 
```
:root {
  --danger-theme: {
    color: white;
    background-color: red;
  }
}

body {
  @apply --danger-theme;
}
```

is causing postcss to show the following error 

```
ERROR in ./~/css-loader?-minimize,sourceMap!./~/postcss-loader?sourceMap=inline!./dashboard/static/dashboard/css/base.css
Module build failed: Error: Expected pseudo-class or pseudo-element
    at new error (/Users/avishayz/workspace/singular/django/node_modules/postcss-selector-parser/dist/processor.js:29:23)
    at Parser.error (/Users/avishayz/workspace/singular/django/node_modules/postcss-selector-parser/dist/parser.js:234:15)
    at Parser.pseudo (/Users/avishayz/workspace/singular/django/node_modules/postcss-selector-parser/dist/parser.js:336:25)
    at Parser.parse (/Users/avishayz/workspace/singular/django/node_modules/postcss-selector-parser/dist/parser.js:553:22)
    at Parser.loop (/Users/avishayz/workspace/singular/django/node_modules/postcss-selector-parser/dist/parser.js:521:18)
    at new Parser (/Users/avishayz/workspace/singular/django/node_modules/postcss-selector-parser/dist/parser.js:104:21)
    at Processor.process (/Users/avishayz/workspace/singular/django/node_modules/postcss-selector-parser/dist/processor.js:26:21)
    at /Users/avishayz/workspace/singular/django/node_modules/postcss-attribute-case-insensitive/dist/index.js:107:68
    at /Users/avishayz/workspace/singular/django/node_modules/postcss/lib/container.js:241:28
    at /Users/avishayz/workspace/singular/django/node_modules/postcss/lib/container.js:148:26
    at Root.each (/Users/avishayz/workspace/singular/django/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/Users/avishayz/workspace/singular/django/node_modules/postcss/lib/container.js:147:21)
    at Root.walkRules (/Users/avishayz/workspace/singular/django/node_modules/postcss/lib/container.js:239:25)
    at /Users/avishayz/workspace/singular/django/node_modules/postcss-attribute-case-insensitive/dist/index.js:106:7
    at LazyResult.run (/Users/avishayz/workspace/singular/django/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/Users/avishayz/workspace/singular/django/node_modules/postcss/lib/lazy-result.js:189:32)
 @ ./dashboard/static/dashboard/css/base.css 4:14-172 13:2-17:4 14:20-178
```

here's my postcss.config.js
```
module.exports = {
    plugins: [
        require('postcss-smart-import')({}),
        require('precss')({}),
        require('autoprefixer')({}),
        require("postcss-import")(),
        require("postcss-url")(),
        require("postcss-browser-reporter")(),
        require("postcss-reporter")(),

        require('postcss-cssnext')({}),

    ]
};
```

using it with webpack1, with postcss-loader as follows:
```
{
 test: /\.css$/,
 loaders: ['style', 'css?-minimize,sourceMap', 'postcss-loader?sourceMap=inline']
  }
```

What am I doing wrong?
Thanks.

**Comment by MoOx** [comment]
The example you are providing is working fine in the [playground](http://cssnext.io/playground/).
Maybe it's a bug related to latest version of a dep. Please open issue at postcss-selector-parser or postcss-attribute-case-insensitive.

Note: your plugin stack is not in the correct order. Order matters. For example, autoprefixer should be the last plugin (and oh it's included in cssnext already). postcss-import should be the first (and oh it's a dup of "smart-import"... reporters should be the last ones... cssnext should be right after import and non standard (precss)...

**Comment by stewartduffy** [comment]
@MoOx do you know of any docs that have a good round up of common PostCss plugins & order they need to be in?
