### ISSUE TITLE
Weird error after updating to 3.x

### ISSUE THREAD

**Issue by stevenvachon** [MoOx/postcss-cssnext#402]
```
Message:
    Parse error on line 1:
-(.8em)
-^
Expecting 'SUB', 'PREFIX', 'NUMBER', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'LPAREN'
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

Downgrading back to 2.11 fixes the issue.

**Comment by MoOx** [comment]
Maybe you can share the problematic piece of CSS? (and the stack trace?)

**Comment by MoOx** [comment]
Closed due to inactivity.

**Comment by wadehammes** [comment]
I just had this same issue, it didn't like this:

`margin-left: calc(-(var(--maven-container-width) / 2) + -(var(--app-flyout-width) / 2));`

So to test the waters, I added some :root variables for the divide-by-2 calculations and got this working, but isn't obviously pretty (but builds):

`margin-left: calc(calc(var(--maven-container-half) + var(--sidebar-half)) * -1);`

Here is the full stack trace:
```
Message:
    Parse error on line 1:
-(20em / 2) + (19.687
-^
Expecting 'SUB', 'PREFIX', 'NUMBER', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'LPAREN'
Details:
    hash: [object Object]
    fileName: /code/app/assets/css/trackmaven.css
Stack:
Error: Parse error on line 1:
-(20em / 2) + (19.687
-^
Expecting 'SUB', 'PREFIX', 'NUMBER', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'LPAREN'
    at Object.parseError (/code/node_modules/postcss-cssnext/node_modules/reduce-css-calc/dist/parser.js:114:19)
    at Object.parse (/code/node_modules/postcss-cssnext/node_modules/reduce-css-calc/dist/parser.js:1:18)
    at /code/node_modules/postcss-cssnext/node_modules/reduce-css-calc/dist/index.js:24:29
    at walk (/code/node_modules/postcss-value-parser/lib/walk.js:10:17)
    at ValueParser.walk (/code/node_modules/postcss-value-parser/lib/index.js:18:5)
    at exports.default (/code/node_modules/postcss-cssnext/node_modules/reduce-css-calc/dist/index.js:19:54)
    at transformValue (/code/node_modules/postcss-cssnext/node_modules/postcss-calc/dist/lib/transform.js:16:31)
    at exports.default (/code/node_modules/postcss-cssnext/node_modules/postcss-calc/dist/lib/transform.js:38:13)
    at /code/node_modules/postcss-cssnext/node_modules/postcss-calc/dist/index.js:18:13
    at /code/node_modules/postcss/lib/container.js:101:31
    at Rule.each (/code/node_modules/postcss/lib/container.js:77:22)
    at Rule.walk (/code/node_modules/postcss/lib/container.js:101:38)
    at /code/node_modules/postcss/lib/container.js:102:18
    at Root.each (/code/node_modules/postcss/lib/container.js:77:22)
    at Root.walk (/code/node_modules/postcss/lib/container.js:101:38)
    at /code/node_modules/postcss-cssnext/node_modules/postcss-calc/dist/index.js:25:9
    at LazyResult.run (/code/node_modules/postcss/lib/lazy-result.js:1:18)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:138:22)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at LazyResult.asyncTick (/code/node_modules/postcss/lib/lazy-result.js:146:13)
    at /code/node_modules/postcss/lib/lazy-result.js:138:13
```

**Comment by MoOx** [comment]
Could you report this to https://github.com/postcss/postcss-calc? Maybe related to https://github.com/postcss/postcss-calc/issues/42

**Comment by Semigradsky** [comment]
> -(var(--maven-container-width) / 2)

@wadehammes  It looks like incorrect syntax. Should be like
```
-1*(var(--maven-container-width) / 2)
```
