### ISSUE TITLE
Error in postcss-calc while updated to 3.0.2

### ISSUE THREAD

**Issue by wenkanglin** [MoOx/postcss-cssnext#405]
the npm logged error info: **Your current PostCSS version is 5.2.17, but postcss-calc uses 6.0.6. Perhaps this is the source of the error below.**

```
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-c84a2b24","scoped":false,"hasInlineConfig":false}!./www-dev/styles/reset.css
Module build failed: TypeError: Cannot read property 'charCodeAt' of undefined
    at module.exports (E:\projects\shangjiditu\node_modules\postcss-value-parser\lib\parse.js:17:21)
    at new ValueParser (E:\projects\shangjiditu\node_modules\postcss-value-parser\lib\index.js:7:22)
    at ValueParser (E:\projects\shangjiditu\node_modules\postcss-value-parser\lib\index.js:10:12)
    at exports.default (E:\projects\shangjiditu\node_modules\postcss-cssnext\node_modules\reduce-css-calc\dist\index.js:29:43)
    at transformValue (E:\projects\shangjiditu\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\lib\transform.js:20:45)
    at E:\projects\shangjiditu\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\lib\transform.js:36:19
    at E:\projects\shangjiditu\node_modules\postcss-selector-parser\dist\selectors\container.js:170:26
    at Selector.each (E:\projects\shangjiditu\node_modules\postcss-selector-parser\dist\selectors\container.js:153:22)
    at Selector.walk (E:\projects\shangjiditu\node_modules\postcss-selector-parser\dist\selectors\container.js:169:21)
    at E:\projects\shangjiditu\node_modules\postcss-selector-parser\dist\selectors\container.js:173:31
    at Root.each (E:\projects\shangjiditu\node_modules\postcss-selector-parser\dist\selectors\container.js:153:22)
    at Root.walk (E:\projects\shangjiditu\node_modules\postcss-selector-parser\dist\selectors\container.js:169:21)
    at Processor.func (E:\projects\shangjiditu\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\lib\transform.js:32:15)
    at Processor.process (E:\projects\shangjiditu\node_modules\postcss-selector-parser\dist\processor.js:34:14)
    at transformSelector (E:\projects\shangjiditu\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\lib\transform.js:46:6)
    at exports.default (E:\projects\shangjiditu\node_modules\postcss-cssnext\node_modules\postcss-calc\dist\lib\transform.js:50:41)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-c84a2b24","scoped":false,"hasInlineConfig":false}!./www-dev/styles/reset.css 4:14-230 13:3-17:5 14:22-238
 @ ./www-dev/app.vue
 @ ./www-dev/main.js
 @ multi ./launcher/webpack-dev/hot-client.js ./www-dev/main.js
```
This is my current packages version:

* postcss 6.0.6
* postcss-cssnext 3.0.2
* postcss-loader 2.0.3

This is my current `node_modules` directory structure about **postcss-calc&postcss-next**:

```
node_modules
|—— postcss // version 6.0.6
|—— postcss-calc // version 5.3.1
|        └── node_modules
|                └── postcss // version 5.2.17
|
|—— postcss-cssnext // version 3.0.2
|       └── node_modules
|                └── postcss-calc // version 6.0.0
```

**Comment by wenkanglin** [comment]
Even if I update the `postcss-calc` to version 6.x, but it cause the same error. I don't know this error whether is caused by `postcss-cssnext` or `postcss-calc`. ==!!

**Comment by MoOx** [comment]
you have a duplicate. `rm -fr node_modules && npm install` should fix the problem if you didn't specify a specific postcss-calc version by hand or if it's not specified by another deps.
