### ISSUE TITLE
Nesting not working, causes processing error

### ISSUE THREAD

**Issue by mkelley33** [MoOx/postcss-cssnext#412]
Note: the error doesn't happen with postcss-cssnext 2.x but does with postcss-cssnext@3.0.2.

Webpack refuses to process my css when I try to nest a rule like so:

```
#app {
  & a {
    color: rebeccapurple;
  }
}
```
The console output is this:

```
Module build failed: TypeError: node.parent.after is not a function
    at module.exports (/node_modules/postcss-nesting/lib/transform-nesting-rule.js:18:29)
    at transform (/node_modules/postcss-nesting/index.js:25:3)
    at /node_modules/vue-loader/node_modules/postcss/lib/container.js:148:26
    at Rule.each (/node_modules/vue-loader/node_modules/postcss/lib/container.js:114:22)
    at Rule.walk (/node_modules/vue-loader/node_modules/postcss/lib/container.js:147:21)
    at /node_modules/vue-loader/node_modules/postcss/lib/container.js:150:32
    at Root.each (/node_modules/vue-loader/node_modules/postcss/lib/container.js:114:22)
    at Root.walk (/node_modules/vue-loader/node_modules/postcss/lib/container.js:147:21)
    at /node_modules/postcss-nesting/index.js:11:24
    at LazyResult.run (/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:201:22)
```

**Comment by RyanZim** [comment]
@mkelley33 Are you using postcss 6?

**Comment by mkelley33** [comment]
@RyanZim It looks like `vue-loader@12.2.2` comes with `postcss@5.2.17`.  I also see that the `postcss-cssnext@3.0.2` I have installed lists `postcss@6.0.9 deduped` in its dependencies.  So, I suspect that my problem is really with vue-loader's older version of postcss. I'll file an issue in the vue-loader repo to update their version of postcss, and keep using postcss-cssnext 2.x in the meantime. Thanks!
