### ISSUE TITLE
Throw error with nesting

### ISSUE THREAD

**Issue by snovey** [MoOx/postcss-cssnext#416]
Enviroment:
- "webpack": "^3.5.2",
- "postcss-cssnext": "^3.0.0",
- "postcss-loader": "^2.0.6",
- "precss": "^2.0.0",
Webpack config:
```javascript
test: /\.vue$/,
use: {
  loader: 'vue-loader',
  options: {
    extractCSS: true,
    postcss: [
      require('postcss-cssnext')(),
      require('precss')()
    ],
    loaders: {
      sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
      scss: 'vue-style-loader!css-loader!sass-loader'
    }
  }
}
```
write css:
```
.title {
  color: #2c3e50;
  font-size: 20px;
  font-weight: bold;
  margin-bottom: 6px;
  &:hover {
    background-color: #4fc08d;
  }
}
```
This code snipped work well with [webpack](https://github.com/vuejs-templates/webpack), but throw error with [electron-vue](https://github.com/SimulatedGREG/electron-vue), Here is error message:
```javascript
  ERROR in ./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-78145104","scoped":false,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/LandingPage.vue
  Module build failed: TypeError: node.parent.after is not a function
      at module.exports (/home/snovey/Documents/my-electron/node_modules/postcss-nesting/lib/transform-nesting-rule.js:18:29)
      at module.exports (/home/snovey/Documents/my-electron/node_modules/postcss-nesting/lib/transform.js:16:3)
      at /home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:148:26
      at Rule.each (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:114:22)
      at Rule.walk (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:147:21)
      at /home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:150:32
      at Root.each (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:114:22)
      at Root.walk (/home/snovey/Documents/my-electron/node_modules/postcss/lib/container.js:147:21)
      at /home/snovey/Documents/my-electron/node_modules/postcss-nesting/index.js:9:24
      at LazyResult.run (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:274:20)
      at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:189:32)
      at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:201:22)
      at processing.Promise.then._this2.processed (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:228:20)
      at Promise (<anonymous>)
      at LazyResult.async (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:225:27)
      at LazyResult.then (/home/snovey/Documents/my-electron/node_modules/postcss/lib/lazy-result.js:131:21)
      at loadPostcssConfig.then.config (/home/snovey/Documents/my-electron/node_modules/vue-loader/lib/style-compiler/index.js:58:8)
   @ ./node_modules/vue-style-loader!./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-78145104","scoped":false,"hasInlineConfig":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/renderer/components/LandingPage.vue 4:14-310 13:3-17:5 14:22-318
   @ ./src/renderer/components/LandingPage.vue
   @ ./src/renderer/router/index.js
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```
Then I downgrading back to version `2.11.0`, It works well.

**Comment by MoOx** [comment]
Looks like it's a postcss-nesting issue according to the stack trace. Please see overthere.
Btw, you should load precss (non standard CSS) before cssnext.

**Comment by snovey** [comment]
```css
.title {
  color: #2c3e50;
  font-size: 20px;
  font-weight: bold;
  margin-bottom: 6px;
  &:hover {
    background-color: #4fc08d;
  }
}
```
Sorry, I forget to say the above code snippet is write in `./src/render/components/LandingPage.vue` file.

After change load precss before cssnext, version `2.11.0` throw the same error too.

**Comment by MoOx** [comment]
Again, the stack trace show a problem in postcss-nesting so please open an issue to this repo.
