### ISSUE TITLE
Errors When Running Jest Unit Tests

### ISSUE THREAD

**Issue by pahund** [MoOx/postcss-cssnext#439]
We have a project that uses Express, React, _postcss-cssnext_ and Jest unit tests.

Since 9. January 2018, when we run our tests, we get multiple errors on varying tests. All have the same stack trace:

    TypeError: Cannot read property 'filename' of undefined

      at Function.Object.<anonymous>.Module._load (node_modules/mock-require/index.js:12:49)
      at Module.require (module.js:497:17)
      at Object.<anonymous> (node_modules/@std/esm/index.js:1:1466)
      at i (node_modules/@std/esm/index.js:1:1090)
      at Object.<anonymous> (node_modules/@std/esm/index.js:1:1509)
      at i (node_modules/@std/esm/index.js:1:1090)
      at Object.<anonymous> (node_modules/@std/esm/index.js:1:165398)
      at i (node_modules/@std/esm/index.js:1:1090)
      at node_modules/@std/esm/index.js:1:1428
      at node_modules/@std/esm/index.js:1:1439
      at load (node_modules/@std/esm/index.js:33:3)
      at Object.<anonymous> (node_modules/@std/esm/index.js:42:10)
      at Object.<anonymous> (node_modules/postcss-font-family-system-ui/src/index.js:2:11)
      at Object.fontFamilySystemUi (node_modules/postcss-cssnext/lib/features.js:96:12)
      at node_modules/postcss-cssnext/lib/index.js:79:44
      at Array.forEach (native)
      at node_modules/postcss-cssnext/lib/index.js:65:35
      at creator (node_modules/postcss/lib/postcss.js:150:35)
      at Object.<anonymous> (scripts/utils/setup-jest.js:27:5)
      at next (native)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:744:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

After some research, my colleague and I have found that there was a patch release 2.1.2 of [postcss-font-family-system-ui](https://github.com/JLHwung/postcss-font-family-system-ui/releases/tag/2.1.2) on the same day that the builds started failing.

_Postcss-cssnext_ has a minor-level dependency to _postcss-font-family-system-ui_, version 2.0.1, so a new, clean build pulled in the faulty module.

As a workaround, we've fixed our build for now by adding a exact-version dev dependency to our project:

    npm install --save-dev --save-exact postcss-font-family-system-ui@2.0.1

**Comment by MoOx** [comment]
I guess you should open an issue over there. We cannot fix this kind of things and I prefer not to have to pin versions.

**Comment by MoOx** [comment]
Current master is perfectly working and postcss-font-family-system-ui as been upgraded to 3. Please reopen if you still have a problem with latest version.

**Comment by pahund** [comment]
💯 I can confirm that the issue is fixed, my Jest tests run as smoothly as ever. **Thank you very much, and keep up the great work!** 💯
